repos:
  - repo: local
    hooks:
      - id: secretlint
        name: secretlint
        language: docker_image
        entry: secretlint/secretlint:latest secretlint
      - id: spotless
        name: spotless check
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
        files: "\\.(kt|kts|xml|json|md)$"
      - id: detekt
        name: detekt
        entry: ./gradlew detekt
        language: system
        pass_filenames: false
        files: "\\.(kt|kts)$"
      - id: unit-tests
        name: unit tests
        entry: ./gradlew testDebugUnitTest
        language: system
        pass_filenames: false
        files: "\\.(kt|kts)$"
