name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: "21"
          cache: gradle

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest jacocoTestReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: jacoco-test-report
          path: app/build/reports/jacoco/jacocoTestReport
          retention-days: 7

      - name: Build Debug APK
        run: ./gradlew assembleDebug
